#!/usr/bin/env bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Verifies every consumer of Node.js agrees on the major version declared
# in .nvmrc.
#
# The frontend lockfile is regenerated by whichever npm ships with the Node
# major in use. When consumers disagree, one of them can silently produce a
# lockfile the others reject -- the failure mode documented in
# docs/design/frontend-lockfile-package-manager-pin.md.
#
# CI reads .nvmrc directly via actions/setup-node's node-version-file, so it
# cannot drift. Dockerfile and cloudbuild-bootstrap.yaml pin an image tag and
# have no way to read .nvmrc, so they are checked here.

set -euo pipefail

cd "$(dirname "$0")/.."

fail=0

expected="$(tr -d '[:space:]' < .nvmrc)"
if [[ -z "$expected" ]]; then
  echo "check-node-versions: .nvmrc is empty or missing" >&2
  exit 1
fi

echo "Expected Node major (.nvmrc): ${expected}"

check() {
  local label="$1" file="$2" pattern="$3"
  local found
  found="$(grep -oE "$pattern" "$file" | head -1 | grep -oE '[0-9]+' | head -1 || true)"

  if [[ -z "$found" ]]; then
    echo "  MISSING  ${label}: no Node version found in ${file}" >&2
    fail=1
  elif [[ "$found" != "$expected" ]]; then
    echo "  MISMATCH ${label}: ${file} pins Node ${found}, expected ${expected}" >&2
    fail=1
  else
    echo "  ok       ${label}: Node ${found}"
  fi
}

check "Dockerfile"     Dockerfile               'FROM node:[0-9]+'
check "Cloud Build"    cloudbuild-bootstrap.yaml 'name: node:[0-9]+'

if [[ "$fail" -ne 0 ]]; then
  cat >&2 <<EOF

Node version drift detected.

Every consumer must build against the same Node major so the npm that
regenerates web/*/package-lock.json is consistent. Update the files listed
above to match .nvmrc (${expected}), or change .nvmrc and update them all.
EOF
  exit 1
fi

echo "All Node versions agree on major ${expected}."
