# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gen_proto/gateway/gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gen_proto/gateway/gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fgen_proto/gateway/gateway.proto\x12\x07gateway\"6\n\x06Origin\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\"\xe1\x01\n\x07Wrapper\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\x12\x1f\n\x06origin\x18\x06 \x01(\x0b\x32\x0f.gateway.Origin\x12\x13\n\x0b\x64\x65stination\x18\x07 \x03(\t\x12\x0e\n\x06status\x18\x08 \x01(\t\x12\r\n\x05\x65vent\x18\t \x01(\t\x12\x10\n\x08metadata\x18\n \x01(\x0c\x12\x15\n\rsimulation_id\x18\x0b \x01(\t\"N\n\x10\x42roadcastRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x1a\n\x12target_session_ids\x18\x02 \x03(\t\x12\r\n\x05\x61sync\x18\x03 \x01(\x08\"H\n\rBatchResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12#\n\tresponses\x18\x02 \x03(\x0b\x32\x10.gateway.Wrapper\"\x8d\x01\n\x0fToolCallRequest\x12\x15\n\rresource_type\x18\x01 \x01(\t\x12\x34\n\x06params\x18\x02 \x03(\x0b\x32$.gateway.ToolCallRequest.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"/\n\x10ToolCallResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"F\n\nA2UIAction\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63tion_name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\x0c\x42\x41Z?github.com/GoogleCloudPlatform/race-condition/gen_proto/gatewayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gen_proto.gateway.gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z?github.com/GoogleCloudPlatform/race-condition/gen_proto/gateway'
  _globals['_TOOLCALLREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_TOOLCALLREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_ORIGIN']._serialized_start=44
  _globals['_ORIGIN']._serialized_end=98
  _globals['_WRAPPER']._serialized_start=101
  _globals['_WRAPPER']._serialized_end=326
  _globals['_BROADCASTREQUEST']._serialized_start=328
  _globals['_BROADCASTREQUEST']._serialized_end=406
  _globals['_BATCHRESPONSE']._serialized_start=408
  _globals['_BATCHRESPONSE']._serialized_end=480
  _globals['_TOOLCALLREQUEST']._serialized_start=483
  _globals['_TOOLCALLREQUEST']._serialized_end=624
  _globals['_TOOLCALLREQUEST_PARAMSENTRY']._serialized_start=579
  _globals['_TOOLCALLREQUEST_PARAMSENTRY']._serialized_end=624
  _globals['_TOOLCALLRESPONSE']._serialized_start=626
  _globals['_TOOLCALLRESPONSE']._serialized_end=673
  _globals['_A2UIACTION']._serialized_start=675
  _globals['_A2UIACTION']._serialized_end=745
# @@protoc_insertion_point(module_scope)
